name: app
description: "Drowsiness Detection App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get:
  google_fonts:
  fluttertoast:
  loading_overlay:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  camera:
  flutter_vision:
  image:
  audioplayers:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

